version: '3'
services:
  motor:
    build: ./Motor
    image: misalcedo/rapbot:motor-1.0
    volumes:
      - ./Motor/src/main/python:/usr/src/app
    ports:
      - 3000:80
    devices:
      - /dev/i2c-1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  vision:
    build: ./Vision
    image: misalcedo/rapbot:vision-1.0
    volumes:
      - ./Vision:/usr/src/app
    ports:
      - 3001:80
    devices:
      - /dev/vchiq
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  hub:
    build: ./Hub
    image: misalcedo/rapbot:hub-1.0
    volumes:
      - ./Hub/build:/usr/src/app/build
    ports:
      - 3002:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname == Fayt
  ui:
    build: ./WebUI
    image: misalcedo/rapbot:ui-1.0
    volumes:
      - ./WebUI/src:/usr/src/app/src
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml