version: '3'
services:
  motor:
    build: ./Motor
    image: misalcedo/rapbot:motor-1.0
    volumes:
      - ./Motor:/usr/src/app
    ports:
      - 3000:80
    devices:
      - /dev/i2c-1
  vision:
    build: ./Vision
    image: misalcedo/rapbot:vision-1.0
    volumes:
      - ./Vision:/usr/src/app
    ports:
      - 3001:80
    devices:
      - /dev/vchiq
  hub:
    build: ./Hub
    image: misalcedo/rapbot:hub-1.0
    volumes:
      - ./Hub/build:/usr/src/app/build
    ports:
      - 3002:80
  ui:
    build: ./WebUI
    image: misalcedo/rapbot:ui-1.0
    volumes:
      - ./WebUI/src:/usr/src/app/src
    ports:
      - 3003:80
  learn:
      build: ./Learn
      image: misalcedo/rapbot:learn-1.0
      volumes:
        - ./Learn/src:/home/jovyan/notebooks
        - ./data/:/home/jovyan/data
      ports:
        - 3004:8888