version: '3'
services:
  motor-service:
    build: ./src/main/python/motor
    volumes:
      - ./src/main/python/motor:/usr/scr/app
    ports:
      - 3000:80
  robot:
    build: ./src/main/java
    depends_on:
      - motor-service