version: '3'
services:
  motor-service:
    build: ./Motor
    volumes:
      - ./Motor/src/main/python:/usr/scr/app
    ports:
      - 3000:80
  robot:
    build: ./Hub
    depends_on:
      - motor-service