version: '3'
services:
  server:
    build: ./server
    ports:
      - 3000:80
  client:
    build: ./client
    ports:
      - 3001:80
  protoc:
    build: ./protoc
    image: misalcedo/rapbot:protoc-1.0
